### ISSUE TITLE
Provide contributor contact instead of “place”

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-ids#12]
This:

https://github.com/ietf-ribose/relaton-data-ids/blob/d30e8cc56a5fc020c16f40b0c0b452ebd2cfdf57/data/draft-3k1n-6tisch-alice0-00.yaml#L115-L116

Should probably reside within contacts here:

https://github.com/ietf-ribose/relaton-data-ids/blob/d30e8cc56a5fc020c16f40b0c0b452ebd2cfdf57/data/draft-3k1n-6tisch-alice0-00.yaml#L26-L32

**Comment by rjsparks** [comment]
Do not try to put an address on the IETF.
Freemont is not not right at all.
"The Internet" would be closer.
But remaining silent is the right thing to do.

**Comment by larseggert** [comment]
+1 on not having a place.

Could someone explain what a `contributor` status signifies? I'd agree that he IETF is a `publisher` of Internet-Drafts, but the plain English definition of `contributor`  has connotations that are unlikely to make sense here.

**Comment by rjsparks** [comment]
Listing the IETF as a contributor in this block is a new concept. While being the publisher is arguably not wrong, claiming that the publisher is a contributor is a new semantic, and has consequences with the IETFs definition of contributor.

I think this block should be removed from the contributor: block altogether.

**Comment by strogonoff** [comment]
> +1 on not having a place.
> 
> Could someone explain what a `contributor` status signifies? I'd agree that he IETF is a `publisher` of Internet-Drafts, but the plain English definition of `contributor` has connotations that are unlikely to make sense here.

I believe there may be a clash between different semantics assigned to “contributor”.

Relaton’s model uses “contributor” to contain every entity that participated in the creation of the document, including editors, translators, authors and publishers. The role of the contributor is reflected via the “role” property.

Some background: the service uses Relaton as internal bibliographic data format. The format was designed to accommodate documents by any SDO. As a result of that, semantics will inevitably clash, but since the format is ultimately internal, they can be dealt with at the display layer: if the term “contributor” should not be shown in the GUI like it does now, this can be accommodated much more easily than e.g. requesting a change to the specification and updating all data sources.


 IETF’s documents semantics

While I am not among core developers of the specification, I believe this is a sane and normalized way to deal with the issue.

The entries from the contributor field can be shown under a different label in GUI, if needed. They are already output under `<author>` in requested BibXML.

**Comment by strogonoff** [comment]
> Could someone explain what a `contributor` status signifies? I'd agree that he IETF is a `publisher` of Internet-Drafts, but the plain English definition of `contributor` has connotations that are unlikely to make sense here.

Some background: the service uses Relaton as internal bibliographic item format. The format was designed to accommodate documents by any SDO, as a result of which semantics across SDOs may clash.

In this case, I believe Relaton’s data model uses the “contributor” property to describe every entity that participated in the creation of the document, including editors, translators, authors and publishers. The role of the contributor is reflected via the “role” property. Presumably, spec designers believed that “contributor” is a generic enough term, but it turns out it clashes with “contributor” as used by IETF.

I believe Relaton spec could be reviewed regarding the naming of the “contributor” property, and this part of the spec could be updated (cc @ronaldtse?). However, since the format is ultimately internal, I’d put forward that issues like these could be dealt with at the display layer of IETF BibXML service rather than the data source.

That is to say, if the term “contributor” should not appear in the GUI in such context, this can be accommodated. Web GUI was initially built to pass through Relaton property names for simplicity, but it was not an explicit design decision and can (should?) be changed with little effort.

(Sorry for duplicate comment, I didn’t expect GitHub to interpret Cmd+Enter as submit shortcut.)

**Comment by rjsparks** [comment]
Even having the notion appear in a publicly accessible intermediate format this way is going to be problematic.

**Comment by strogonoff** [comment]
Fair enough. @ronaldtse @opoudjis it looks like the use of Relaton for this project may not be possible unless the `contributor` field is renamed due to vocabulary clash, could we use a more explicit and precise term? For example, `participant`, `involved_party` or something like that.

**Comment by strogonoff** [comment]
For the record, here’s the list of possible roles a contributor (per Relaton’s concept) can have so far:

```"author" | "performer" | "publisher" | "editor" | "adapter" | "translator" | "distributor"```

**Comment by rjsparks** [comment]
Trying to follow the above suggestion. Just renaming the container isn't going to address the whole issue. This idea of throwing the IETF into a container with the authors with a formal role of "publisher" is, I think, going to be problematic regardless of the container name.

And while you're thinking about this in addition to "contributor" meaning something special from the IETF's IPR rules point of view, there is a not-tightly-defined concept of a "contributor's" section being used in many drafts and RFCs at this point and it is not an appropriate time to put this in the same bucket with authors in the references.

**Comment by rjsparks** [comment]
>For the record, here’s the list of possible roles a contributor (per Relaton’s concept) can have so far:

does can imply must?

**Comment by strogonoff** [comment]
> And while you're thinking about this in addition to "contributor" meaning something special from the IETF's IPR rules point of view, there is a not-tightly-defined concept of a "contributor's" section being used in many drafts and RFCs at this point and it is not an appropriate time to put this in the same bucket with authors in the references.

I see. That was my initial interpretation, I stand corrected and since I’m removed from relevant context I’ll abstain from any further suggestions and leave it to spec development team to sort out.

> does can imply must?

I think those are just available values of `contributor[*].role` in Relaton data model.

**Comment by ronaldtse** [comment]
@rjsparks we can definitely omit the Publisher "place". Just to clarify that there are typically two "places" allowed in a reference:

* Place of the publisher. This is from traditional citation practice (and used in ISO 690)
* Place of individual contributors. This is the per-contributor address. A publisher "could" be a contributor, but it may not be.

So we will remove mention of the Publisher "place" (which is of course optional).

**Comment by ronaldtse** [comment]
For the record, the semantics of "contributor" mirror the ISO 690 data element "Creator", of which the partial description is provided below:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/11865/152890616-7b382203-9bb7-4573-aa9e-4d3f21b83e58.png">

The semantics of "Place" is described in ISO 690 "Production information".
<img width="790" alt="Screenshot 2022-02-08 at 7 40 35 AM" src="https://user-images.githubusercontent.com/11865/152890554-40ef433f-e58c-49dc-b841-e92099a2dcc8.png">

**Comment by strogonoff** [comment]
I think after @andrew2net’s change this can be closed.
