### ISSUE TITLE
Primary identifiers for Internet Drafts

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-ids#13]
Currently, Relaton data provides document identifiers for Internet Drafts like this:

https://github.com/ietf-ribose/relaton-data-ids/blob/63bd977c0359878c956b9ad5d3850c33e55a88db/data/draft-ietf-intarea-tunnels-10.yaml#L14-L22

Note the pattern marked as “primary”. Presumably, this is the one suggested to be used when citing, and it has the format `I-D ietf-intarea-tunnels`.

From my understanding, IETF uses `draft-ietf-intarea-tunnels` when citing (Datatracker returns those, too). Do we want to include this identifier and indicate it as `primary` to conform to real-life use scenarios but violate Relaton’s wider schema? (Or am I misunderstanding something and `I-D ietf-intarea-tunnels` is in fact used?)

**Comment by ronaldtse** [comment]
@strogonoff `draft-ietf-intarea-tunnels` is definitely one "primary" identifier.

The pattern `I-D.xxx` is used in xml2rfc, which is the authoritative tool used to create IETF documents:
https://www.ietf.org/proceedings/65/slides/xml2rfc-0.pdf

e.g.
```
<!ENTITY dos-draft PUBLIC "" 'http://xml.resource.org/public/rfc/bibxml3/reference.I-D.iab-dos.xml'> ]>
```

<img width="1056" alt="Screenshot 2022-02-16 at 2 11 29 AM" src="https://user-images.githubusercontent.com/11865/154123119-3b5236ee-7fcd-4474-99f2-b65f1cd01db1.png">

But `I-D ietf-intarea-tunnels` is probably not the primary identifier.

Ping @andrew2net .

**Comment by TonyLHansen** [comment]
I would call the -10 identifier as primary, with the value without the -10 as secondary. After all, the -10 identifier uniquely identifies a particular version of a draft.

The same would be true for the -09, -08, -07, etc versions.

But I'm not sure what connotations there are for the identifier to be primary.

**Comment by strogonoff** [comment]
The connotation, from what I understand, is just that authors can use that exact string to unambiguously reference/cite a document. (E.g., DOI and ISBN are also identifiers, but no one cites by DOI or ISBN, so Relaton data does not mark them as primary.)

**Comment by andrew2net** [comment]
> But `I-D ietf-intarea-tunnels` is probably not the primary identifier.

@ronaldtse as I understand the primary ID is used to cite a document. The `relatnon-*` gems accept primary ID as an argument to get a document.

**Comment by ronaldtse** [comment]
>  I understand the primary ID is used to cite a document. The relatnon-* gems accept primary ID as an argument to get a document.

Relaton has to accept any ID (primary or not primary) used to cite a document. The "primary" tag is only useful when a reading application wants to display the ID. @andrew2net can you file a ticket at the appropriate place? Thanks.

**Comment by strogonoff** [comment]
> > I understand the primary ID is used to cite a document. The relatnon-* gems accept primary ID as an argument to get a document.
> 
> Relaton has to accept any ID (primary or not primary) used to cite a document. The "primary" tag is only useful when a reading application wants to display the ID. @andrew2net can you file a ticket at the appropriate place? Thanks.

I thought Relaton enforces `primary` usage. If it doesn’t, it will allow authors to cite by DOI, and from my understanding this should not be the case.

**Comment by strogonoff** [comment]
I agree on search, I meant using any non-primary docid when citing/referencing.

**Comment by ronaldtse** [comment]
@andrew2net For data sources that we need to "search on an external service" it would be difficult to allow searching using other criteria. However, for the data sources that we have a full dataset, we can create indexes using those other kinds of IDs too.

**Comment by ronaldtse** [comment]
@strogonoff is this task still valid? The anchor used by I-D is correct as per here: https://github.com/ietf-ribose/bibxml-service/issues/151#issuecomment-1064218979

**Comment by strogonoff** [comment]
@ronaldtse I think this issue has been superseded by https://github.com/ietf-ribose/relaton-data-ids/issues/14.
