### ISSUE TITLE
Designate an unversioned docid as primary

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-ids#15]
Based on discussion in https://github.com/ietf-ribose/relaton-data-ids/issues/14.

- `docid.primary` should be `true`
- `docid.scope` should be unspecified 
- `docid.id` should be unversioned

I am not sure which exact form is better (perhaps @ronaldtse can weigh in on this), for example:

1. `{ id: "I-D sparks-sipcore-multiple-reasons", type: "IETF" }`
2. `{ id: "draft-sparks-sipcore-multiple-reasons", type: "Internet-Draft" }`

**Comment by ronaldtse** [comment]
Thanks for the ping @strogonoff . I don't know the correct answer.

Considerations:
* I would think the proper ID for `draft-sparks-sipcore-multiple-reasons` omits the `draft-`.
* We shouldn't use `type: "IETF"` because IETF has stated multiple times they don't want to be associated with Internet-Drafts and RFCs.
* There is no "correct" PubID for Internet-Drafts today.

I have sent a clarification request to IETF and let's see what the reply is.

**Comment by strogonoff** [comment]
@ronaldtse 

If we want to use neither `draft-` prefix nor `IETF` type, I am OK using this:

    { id: "I-D sparks-sipcore-multiple-reasons", type: "Internet-Draft" }

However, this would break the preexisting pattern where for `I-D ` prefixes the identifier type is “IETF”.

Until now we were basically saying “type _Internet-Draft_ means id starts with `draft-`; type _IETF_ means id starts with `I-D.` (or `RFC`, for RFCs)”.

	docid:
	- id: draft-3gpp-collaboration-01
	  type: Internet-Draft
	  primary: true
	- id: I-D.3gpp-collaboration
	  type: IETF
	  scope: anchor

Now we will be saying “type _Internet-Draft_ means id starts with `draft-` _or_ `I-D `; type _IETF_ means id starts with `I-D.`”:

	docid:
	- id: draft-3gpp-collaboration-01
	  type: Internet-Draft
	  primary: true
	- id: I-D.3gpp-collaboration
	  type: IETF
	  scope: anchor
	- id: I-D 3gpp-collaboration
	  type: IETF
	  primary: true

**Comment by strogonoff** [comment]
Asked Nick to see what he thinks

**Comment by ronaldtse** [comment]
This will be implemented in https://github.com/relaton/relaton-ietf/issues/74

**Comment by strogonoff** [comment]
Closing this in favor of that.
