### ISSUE TITLE
Why are all file names in all caps?

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/relaton-data-ids#3]
If they are in all caps, they could also be in all lowercase.

Change them to all lowercase. All caps does not provide any benefit.

**Comment by andrew2net** [comment]
@ronaldtse I think all caps or all lowercase are useful for users because they don't need to care about caps.
I'll change it all to lowercase.

**Comment by ronaldtse** [comment]
Thanks @andrew2net . Lowercase is the convention in Internet-Draft IDs.

**Comment by andrew2net** [comment]
fixed
