### ISSUE TITLE
No metadata differentiation between draft versions

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-ids#9]
Here is an item that is presumably version 2 of a document:

https://github.com/ietf-ribose/relaton-data-ids/blob/main/data/draft-donley-behave-deterministic-cgn-02.yaml

However, nowhere in Relaton data is version 2 specified in a normalized way.

Some of the fields that could be used for this:

- [version](https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc#L450)?
- [vedition](https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc#L455)?
- [edition](https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc#L51)?
- [series.number](https://github.com/relaton/relaton-models/blob/main/models/SeriesType.lutaml#L51)?

**Comment by ronaldtse** [comment]
@strogonoff for these issues that relate to Relaton, please file them in the corresponding Relaton repositories. @andrew2net needs to know about them to fix them.
